"""Generates the Openbox configuration that matches the active style."""

import os
import shutil

from . import paths
from .config import CONFIG_DIR
from .gtk import GLib

RC_PATH = os.path.join(CONFIG_DIR, "openbox", "rc.xml")

_FONT = """<font place="{place}"><name>{family}</name><size>{size}</size><weight>{weight}</weight><slant>normal</slant></font>"""

_MOUSE = """
    <dragThreshold>3</dragThreshold>
    <doubleClickTime>400</doubleClickTime>
    <screenEdgeWarpTime>0</screenEdgeWarpTime>
    <context name="Frame">
      <mousebind button="A-Left" action="Press"><action name="Focus"/><action name="Raise"/></mousebind>
      <mousebind button="A-Left" action="Drag"><action name="Move"/></mousebind>
      <mousebind button="A-Right" action="Drag"><action name="Resize"/></mousebind>
    </context>
    <context name="Titlebar">
      <mousebind button="Left" action="Drag"><action name="Move"/></mousebind>
      <mousebind button="Left" action="DoubleClick"><action name="ToggleMaximize"/></mousebind>
    </context>
    <context name="Titlebar Top Right Bottom Left TLCorner TRCorner BRCorner BLCorner">
      <mousebind button="Left" action="Press"><action name="Focus"/><action name="Raise"/><action name="Unshade"/></mousebind>
      <mousebind button="Middle" action="Press"><action name="Lower"/><action name="FocusToBottom"/><action name="Unfocus"/></mousebind>
      <mousebind button="Right" action="Press"><action name="Focus"/><action name="Raise"/><action name="ShowMenu"><menu>client-menu</menu></action></mousebind>
    </context>
    <context name="Top"><mousebind button="Left" action="Drag"><action name="Resize"><edge>top</edge></action></mousebind></context>
    <context name="Left"><mousebind button="Left" action="Drag"><action name="Resize"><edge>left</edge></action></mousebind></context>
    <context name="Right"><mousebind button="Left" action="Drag"><action name="Resize"><edge>right</edge></action></mousebind></context>
    <context name="Bottom"><mousebind button="Left" action="Drag"><action name="Resize"><edge>bottom</edge></action></mousebind></context>
    <context name="TRCorner BRCorner TLCorner BLCorner"><mousebind button="Left" action="Drag"><action name="Resize"/></mousebind></context>
    <context name="Client">
      <mousebind button="Left" action="Press"><action name="Focus"/><action name="Raise"/></mousebind>
      <mousebind button="Middle" action="Press"><action name="Focus"/><action name="Raise"/></mousebind>
      <mousebind button="Right" action="Press"><action name="Focus"/><action name="Raise"/></mousebind>
    </context>
    <context name="Icon">
      <mousebind button="Left" action="Press"><action name="Focus"/><action name="Raise"/><action name="ShowMenu"><menu>client-menu</menu></action></mousebind>
    </context>
    <context name="AllDesktops"><mousebind button="Left" action="Click"><action name="ToggleOmnipresent"/></mousebind></context>
    <context name="Shade"><mousebind button="Left" action="Click"><action name="ToggleShade"/></mousebind></context>
    <context name="Iconify"><mousebind button="Left" action="Click"><action name="Iconify"/></mousebind></context>
    <context name="Maximize">
      <mousebind button="Left" action="Click"><action name="ToggleMaximize"/></mousebind>
      <mousebind button="Middle" action="Click"><action name="ToggleMaximize"><direction>vertical</direction></action></mousebind>
      <mousebind button="Right" action="Click"><action name="ToggleMaximize"><direction>horizontal</direction></action></mousebind>
    </context>
    <context name="Close"><mousebind button="Left" action="Click"><action name="Close"/></mousebind></context>
    <context name="Desktop">
      <mousebind button="Left" action="Press"><action name="Focus"/><action name="Raise"/></mousebind>
    </context>
    <context name="Root">
      <mousebind button="Middle" action="Press"><action name="ShowMenu"><menu>client-list-combined-menu</menu></action></mousebind>
    </context>
"""

_TEMPLATE = """<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by HyperNova for the "{style_name}" style. Edits are overwritten when the style changes. -->
<openbox_config xmlns="http://openbox.org/3.4/rc" xmlns:xi="http://www.w3.org/2001/XInclude">
  <resistance><strength>10</strength><screen_edge_strength>20</screen_edge_strength></resistance>
  <focus>
    <focusNew>yes</focusNew><followMouse>no</followMouse><focusLast>yes</focusLast>
    <underMouse>no</underMouse><focusDelay>200</focusDelay><raiseOnFocus>no</raiseOnFocus>
  </focus>
  <placement><policy>Smart</policy><center>yes</center><monitor>Primary</monitor><primaryMonitor>1</primaryMonitor></placement>
  <theme>
    <name>{theme}</name>
    <titleLayout>{title_layout}</titleLayout>
    <keepBorder>yes</keepBorder>
    <animateIconify>yes</animateIconify>
    {fonts}
  </theme>
  <desktops><number>1</number><firstdesk>1</firstdesk><names><name>Masaüstü</name></names><popupTime>0</popupTime></desktops>
  <resize><drawContents>yes</drawContents><popupShow>Nonpixel</popupShow><popupPosition>Center</popupPosition></resize>
  <margins><top>{margin_top}</top><bottom>{margin_bottom}</bottom><left>0</left><right>0</right></margins>
  <keyboard>
    <chainQuitKey>C-g</chainQuitKey>
    <keybind key="A-Tab"><action name="NextWindow"><finalactions><action name="Focus"/><action name="Raise"/><action name="Unshade"/></finalactions></action></keybind>
    <keybind key="A-S-Tab"><action name="PreviousWindow"><finalactions><action name="Focus"/><action name="Raise"/><action name="Unshade"/></finalactions></action></keybind>
    <keybind key="A-F4"><action name="Close"/></keybind>
    <keybind key="W-d"><action name="ToggleShowDesktop"/></keybind>
    <keybind key="W-Up"><action name="Maximize"/></keybind>
    <keybind key="W-Down"><action name="Unmaximize"/></keybind>
    <keybind key="W-Left"><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>0</x><y>0</y><width>50%</width><height>100%</height></action></keybind>
    <keybind key="W-Right"><action name="UnmaximizeFull"/><action name="MoveResizeTo"><x>-0</x><y>0</y><width>50%</width><height>100%</height></action></keybind>
    <keybind key="W-e"><action name="Execute"><command>hypernova-shell --open-home</command></action></keybind>
    <keybind key="W-r"><action name="Execute"><command>hypernova-shell --run</command></action></keybind>
    <keybind key="W-s"><action name="Execute"><command>hypernova-shell --search</command></action></keybind>
    <keybind key="W-i"><action name="Execute"><command>hypernova-settings</command></action></keybind>
    <keybind key="C-A-t"><action name="Execute"><command>hypernova-shell --terminal</command></action></keybind>
    <keybind key="C-Escape"><action name="Execute"><command>hypernova-shell --toggle-menu</command></action></keybind>
    <keybind key="W-space"><action name="Execute"><command>hypernova-shell --toggle-menu</command></action></keybind>
    <keybind key="C-A-Delete"><action name="Execute"><command>hypernova-shell --power</command></action></keybind>
  </keyboard>
  <mouse>{mouse}
  </mouse>
  <menu><hideDelay>200</hideDelay><middle>no</middle><submenuShowDelay>100</submenuShowDelay><applicationIcons>yes</applicationIcons></menu>
  <applications>
    <application name="hypernova-shell" role="hn-popup"><decor>no</decor><focus>yes</focus><layer>above</layer><desktop>all</desktop><skip_taskbar>yes</skip_taskbar></application>
    <application name="hypernova-shell" role="hn-dialog"><decor>no</decor><focus>yes</focus><layer>above</layer><desktop>all</desktop><skip_taskbar>yes</skip_taskbar></application>
  </applications>
</openbox_config>
"""

STYLE_FONTS = {
    "xp": ("Noto Sans", 9),
    "win7": ("Noto Sans", 9),
    "win10": ("Noto Sans", 9),
    "mac": ("Noto Sans", 9),
}


def render(style):
    from .mac import Dock
    family, size = STYLE_FONTS.get(style.id, ("Noto Sans", 9))
    fonts = "\n    ".join(
        _FONT.format(place=place, family=family, size=size, weight=weight)
        for place, weight in (("ActiveWindow", "bold"), ("InactiveWindow", "bold"),
                              ("MenuHeader", "bold"), ("MenuItem", "normal"),
                              ("ActiveOnScreenDisplay", "bold"), ("InactiveOnScreenDisplay", "bold")))
    if style.layout == "mac":
        margin_top, margin_bottom = style.panel_height, Dock.height_for(style) + 6
    else:
        margin_top, margin_bottom = 0, style.panel_height
    return _TEMPLATE.format(style_name=style.name, theme=style.openbox_theme, title_layout=style.title_layout,
                            fonts=fonts, margin_top=margin_top, margin_bottom=margin_bottom, mouse=_MOUSE)


def ensure_themes():
    """In a source checkout, expose the bundled Openbox themes to Openbox."""
    source = paths.data_file("themes")
    if not os.path.isdir(source) or source.startswith("/usr/"):
        return
    target_root = os.path.join(GLib.get_user_data_dir(), "themes")
    os.makedirs(target_root, exist_ok=True)
    for name in os.listdir(source):
        target = os.path.join(target_root, name)
        if not os.path.exists(target):
            os.symlink(os.path.join(source, name), target)


def write_config(style):
    ensure_themes()
    os.makedirs(os.path.dirname(RC_PATH), exist_ok=True)
    tmp = RC_PATH + ".tmp"
    with open(tmp, "w", encoding="utf-8") as fh:
        fh.write(render(style))
    os.replace(tmp, RC_PATH)
    return RC_PATH


def reconfigure():
    if shutil.which("openbox"):
        try:
            GLib.spawn_async(["openbox", "--reconfigure"], flags=GLib.SpawnFlags.SEARCH_PATH)
        except GLib.Error:
            pass
